// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ImageResizer {
	
	
	public partial class UploadImage {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox imgCaption;
		
		protected System.Web.UI.WebControls.FileUpload img;
		
		protected System.Web.UI.WebControls.Label lblStatus;
	}
}
